### ISSUE TITLE
Update the bootstrap version in CDN to the current version 3.3.7

### ISSUE THREAD

**Issue by massamatheus** [JasonMortonNZ/bs3-sublime-plugin#108]
Please update the version to 3.3.7

`
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<script src="//code.jquery.com/jquery.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>`

**Comment by JasonMortonNZ** [comment]
Will update. Thanks :)
