### ISSUE TITLE
No autocomplétion with st3

### ISSUE THREAD

**Issue by SamirBoudaoud** [JasonMortonNZ/bs3-sublime-plugin#75]
hello, i have installed the plugin for st3 but i dont have autocompletion when i put "bs3-"
i tried with html and php files

**Comment by uschmidt** [comment]
Autocomplete works when i switch the file type to ruby or jade, but it works not with html.

**Comment by SamirBoudaoud** [comment]
does it have any issue to make it compatible with html too ?
