### ISSUE TITLE
textarea input missing

### ISSUE THREAD

**Issue by nicekiwi** [JasonMortonNZ/bs3-sublime-plugin#76]

**Comment by nicekiwi** [comment]
This has been added now?

**Comment by JasonMortonNZ** [comment]
Yep, I've just down a heap of house cleaning (pulling in pull request, etc) and adding new snippets. I've just tagged a new release of this package v1.1.6 so you should get the updates soon :)

**Comment by nicekiwi** [comment]
Awesome :) thanks
