### ISSUE TITLE
<bs3 not working on install

### ISSUE THREAD

**Issue by bconner22** [JasonMortonNZ/bs3-sublime-plugin#86]
Ubuntu 14.04
FIXED.  When I first installed bs3 on sublime 2, I added the "<" trigger to my settings as per your doc... it was already in the default settings, so I added it to my user settings, and the <bs3 autocomplete didn't bring anything up.  Added the trigger to all the other settings, even the html-specific one, nada.  The only other package I had installed was Emmet.  Disabled and uninstalled Emmet, still no dice.  CTRL+Shift+P worked for bs3 no problem since I installed it.  When I finally removed/reinstalled bs3, <bs3 works like a charm, great addon!  

I believe my particular issue may have something to do with needing the preferences saved BEFORE bs3 was installed.  Or maybe it was just a bad install?  Works now and is awesome, thank you for the hard work!

**Comment by msurguy** [comment]
I'm having the same issue on Mac OS X Sublime Text 2.

**Comment by bconner22** [comment]
Hey msurguy, it started happening to me again after i posted this.  I completely removed sublime 2 and installed sublime 3, and now it mostly works.  Only issue is after i use the autocomplete and hit enter to select what i want, an additional < is at the beginning of my line, the one that i used to invoke <bs3.  I have to go and delete it manually, but it's still faster than typing out everything.  Perhaps you could try foing to sublime 3?

**Comment by sidgupta234** [comment]
Ubuntu 14.04, same issues as @bconner22 tried everything removed all packages, installed Bootstrap 3 Snippets still wont work, except sublime 3 any other alternatives, please?

**Comment by bconner22** [comment]
Siddharth,
Try going to sublime 3.





-------- Original message --------

**Comment by sidgupta234** [comment]
Works with sublime 3, only with an extra "<" to begin with.

**Comment by JasonMortonNZ** [comment]
@sidgupta234 Try updating the `"auto_complete_triggers"` setting to this:

`"auto_complete_triggers": [{"selector": "text.html", "characters": "<"},{"selector": "text.html", "characters": "bs3"}]`

**Comment by kirykr** [comment]
@JasonMortonNZ He is the key!!!!!!!!!!!!!!!!!!!
