### ISSUE TITLE
One more character after shortcut

### ISSUE THREAD

**Issue by bagusflyer** [JasonMortonNZ/bs3-sublime-plugin#87]
For example, I input <bs3-label it will become:

```
 <<span class="label">Label</span>
```
One extra < input, what's wrong? Thanks

**Comment by pravin-d** [comment]
:+1:  Same issue

**Comment by stormslowly** [comment]
just type `bs3-xxx`,  the trigger is start with bs3 not <

**Comment by pravin-d** [comment]
bs3-xxx does not start the trigger..  however triggering auto completion manually (ctrl+space) does the trick..

**Comment by tobsn** [comment]
"auto_complete_triggers": [ {"selector": "text.html", "characters": "<"}, {"selector": "text.html", "characters": "bs3"}, {"selector": "text.php", "characters": "<"} ],

worst case "fix"...

**Comment by mixania** [comment]
Can confirm, would be nice if this was fixed without having the user to hack into anything.

**Comment by JasonMortonNZ** [comment]
Thanks @tobsn, your fix appears to be the only way past this issue that I've found.

**Comment by tobsn** [comment]
@JasonMortonNZ yeah, the biggest problem isn't the fix, the problem is that the library isn't updated as far as I can tell

**Comment by tobsn** [comment]
New Features
  ------------------------------------------------------------
  - FIX FOR remaining '<' after autocomplete:
  	* Update your "auto_complete_triggers" setting to this:
  	* "auto_complete_triggers": [{"selector": "text.html", "characters": "<"},{"selector": "text.html", "characters": "bs3"}]
  - Updated CDN references to Bootstrap v3.3.6
  - OUT NOW     - A PHPStorm plugin with all the same snippets

lol you're welcome :D
