### ISSUE TITLE
bootstrap cdn url update and version

### ISSUE THREAD

**Issue by tobsn** [JasonMortonNZ/bs3-sublime-plugin#90]
maxcdn.bootstrapcdn.com
and
obviously 3.3.5

**Comment by tobsn** [comment]
ok added template update too!

please pull :D

**Comment by tobsn** [comment]
also added the maxcdn hosted ie10 workaround script that is now default in all templates

**Comment by edgarshurtado** [comment]
I reallize of the same issue as well. Hope you get pulled soon. Meanwhile I'm going to edit the pluggin

**Comment by edgarshurtado** [comment]
I've thought that better I just clone your repo. One question, why do you leave the cdn without the http: in the url? I'm sure it has to have a reason , but until I didn't write it down, it doesn't work.

**Comment by JasonMortonNZ** [comment]
Will update. Thanks :)
