### ISSUE TITLE
JS cdn is broken.

### ISSUE THREAD

**Issue by GlJS** [JasonMortonNZ/bs3-sublime-plugin#95]
Hey there. Just to attend you. 
<bs3-cdn:js is broken.
It refers to: //netdna.bootstrapcdn.com/bootstrap/js/bootstrap.min.js which access is denied. Please update it! 
I think it had to be: '//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' or something

The CSS cdn still works.

**Comment by GlJS** [comment]
Oh, and they are both outdated too. Bootstrap is currently running on 3.3.6 :)

**Comment by ArunHub** [comment]
Already done by J2team .. but maintainer didnt merge pull request since it conflicts

**Comment by JasonMortonNZ** [comment]
Will update JS link. Thanks :)
